development:
  adapter: sqlite3
  encoding: unicode
  database: parasenok_base
  host: "localhost"
  pool: 5
  username: postgres
  password: "123123"

test:
  adapter: sqlite3
  encoding: unicode
  database: parasenok_base_test
  host: "localhost"
  pool: 5
  username: postgres
  password: "123123"

production:
  adapter: sqlite3
  encoding: unicode
  database: parasenok_base_production
  host: "localhost"
  pool: 5
  username: postgres
  password: "123123"